### ISSUE TITLE
ubuntu install, and issues

### ISSUE THREAD

**Issue by colindaven** [ait5/CNApp#1]
Hi,

interesting looking app.

On ubuntu 16.04 I needed these packages to install everything successfully.

sudo apt install libmariadb-client-lgpl-dev

sudo apt install libv8-3.14-dev

Unfortunately, selecting the demo data doesn't do anything, and the whole app is kind of grey so I must be missing other packages. R-3.4.4

Any ideas ?

**Comment by ait5** [comment]
Hi @colindaven,

thanks a lot for trying out our app!

I have just re-downloaded and re-installed the whole app into my Mac and it works fine (just to be sure anything happened since my last test...).

I haven't tried to install it on Ubuntu 16.0.4 (I have 14.04 at my work-place and it worked fine by testing the installation. Still haven't upgraded my ubuntu OS...).

Any error coming out at R-studio terminal when running the app?? It seems strange that everything is going fine till selecting the demo data... :S

Have you tried to upload data of your own? (or try to use demo data as input data, just as it was your owns!)

Let me know how it goes!!

**Comment by ait5** [comment]
Sorry, @colindaven, I have 16.04 Ubunut installed indeed and all worked fine for me...

**Comment by colindaven** [comment]
hey @ait5 , thanks for looking into this.

I just upgraded my R from 3.4.4 to 3.5 (locally at least),  is R3.5 required ?

**Comment by ait5** [comment]
Hi @colindaven ,

CNApp is working with R 3.4.2 in our server, but I have installed also using new version (e.g. using my Mac with R 3.5.1)

**Comment by colindaven** [comment]
Hey,

the main error which I can't resolve is phantomjs. Is this likely to be a major issue ?

```
2018-12-14 13:26:13 (2,38 MB/s) - ‘phantomjs-2.1.1-linux-x86_64.tar.bz2’ saved [23415665/23415665]

phantomjs has been installed to /home/davenpor/bin
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘phantomjs’
```

**Comment by colindaven** [comment]
Thanks, it works now with Ubuntu 16.04 and R3.5.1, despite the phantomjs warning mentioned above. I had to download the demo data separately and manually add.
